import mongoose from "mongoose";

// make sure orderId was generated by the prisma automatically 
// iam using the mongo generated uniq id but when iam using the postgress then i need to mannually create the id for order
// orderId:{
//     type:String,
//     unique: true,
//     required:true
//   },
const orderSchema = new mongoose.Schema({
  
  orderId: {
    type: String,
    unique: true,
    required: true
  },
  userId: {
    type: String,
    required: true,
    ref: 'user'
  },
  items: [
    {
      product: { type: String, required: true, ref: 'product' },
      quantity: { type: Number, required: true },
      size: { type: String, required: true },
      color: { type: String, required: true }
    }
  ],
  amount: {
    type: Number,
    required: true,
  },
  address: {
    type: String,
    ref: 'address',
    required: true
  },
  status: {
    type: String,
    required: true,
    default: 'order placed'
  },
  isCompleted: {
    type: Boolean,
    default: false
  },
  cancelled: {
    type: Boolean,
    default: false
  },
  payment: {
    type: Boolean,
    default: false
  },
  refunded: { type: Boolean, default: false },
  PaymentId:{type:String,default:null},
  refundId:{type:String,default:null},    
  refundStatus: {type:String,default:'Pending'} ,
  date: {
    type: Number,
    required: true
  }
});

const Order = mongoose.models.order || mongoose.model('order', orderSchema);

export default Order;
